modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"
license="${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"

# updateJSONURL = "https://raw.githubusercontent.com/AGM-Studio/NeoBots/refs/heads/main/update.json"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/create-neobots"
credits = "Made by Love! AGMStudioÂ©"
logoFile = "${mod_id}.png"

authors = "Ashenguard"
description = "A modular programable bot in Create style!"

# [[mixins]]
# config = "${mod_id}.mixins.json"
# [[mixins]]
# config = "${mod_id}.neoforge.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neoforge_version_range}"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
side="BOTH"

[[dependencies.${mod_id}]]
modId="create"
type="required"
versionRange="${create_version_range}"
side="BOTH"